### ISSUE TITLE
Feature Request: Socket timeouts

### ISSUE THREAD

**Issue by eric** [copiousfreetime/kjess#1]
It would be worth providing a way to have socket timeouts for reading and writing.

It would be even better if it also took the specified get timeout into account with it...

**Comment by eric** [comment]
One solution from redis-rb: https://github.com/redis/redis-rb/blob/master/lib/redis/connection/ruby.rb#L7-159

**Comment by eric** [comment]
Another solution from dalli: https://github.com/mperham/dalli/blob/master/lib/dalli/socket.rb

**Comment by copiousfreetime** [comment]
Fixed with version 1.1.0 released today
