### ISSUE TITLE
KJess::Socket's `@socket` is `0`

### ISSUE THREAD

**Issue by technoweenie** [copiousfreetime/kjess#14]
I'm seeing a funny error on my staging server.

```
>> client.stats
NoMethodError: undefined method `write_nonblock' for 0:Fixnum
    from /data/hookshot/vendor/gems/ruby/1.8/gems/kjess-1.1.0/lib/kjess/socket.rb:280:in `write'
    from /data/hookshot/vendor/gems/ruby/1.8/gems/kjess-1.1.0/lib/kjess/connection.rb:129:in `write'
    from /data/hookshot/vendor/gems/ruby/1.8/gems/kjess-1.1.0/lib/kjess/client.rb:302:in `send_recv'
    from /data/hookshot/vendor/gems/ruby/1.8/gems/kjess-1.1.0/lib/kjess/client.rb:258:in `stats!'
    from /data/hookshot/vendor/gems/ruby/1.8/gems/kjess-1.1.0/lib/kjess/stats_cache.rb:25:in `stats'
    from /data/hookshot/vendor/gems/ruby/1.8/gems/kjess-1.1.0/lib/kjess/client.rb:248:in `stats'
```

I can connect to it just fine from the server through telnet though:

```
$ telnet SERVER PORT
Trying SERVER...
Connected to SERVER.
Escape character is '^]'.
stats
STAT uptime 161937
STAT time 1365969519
STAT version 2.4.1
```

Any idea how `@socket` gets set to `0`?

**Comment by eric** [comment]
That is really odd.

I have to admit I am not using the kjess stats call (I had previously written one when I was using `kestrel-client` and am still using that), so it's possible the stats call has not been well-tested in production.

**Comment by technoweenie** [comment]
It's coming from KJess::Socket#socket.

```
s=c.connection.socket
=> #<KJess::Socket:0x7f6f13823be0 @socket=nil, @port=22134,
@keepalive_active=true, @read_timeout=2, @host="172.19.0.46",
@keepalive_count=5, @write_timeout=2, @keepalive_idle=60,
@keepalive_interval=30, @connect_timeout=2>
>> s.socket
=> 0
>> p s
#<KJess::Socket:0x7f6f13823be0 @socket=0, @port=22134,
@keepalive_active=true, @read_timeout=2, @host="172.19.0.46",
@keepalive_count=5, @write_timeout=2, @keepalive_idle=60,
@keepalive_interval=30, @connect_timeout=2>
=> nil
```

On Sun, Apr 14, 2013 at 2:07 PM, Eric Lindvall notifications@github.comwrote:

> That is really odd.
> 
> I have to admit I am not using the kjess stats call (I had previously
> written one when I was using kestrel-client and am still using that), so
> it's possible the stats call has not been well-tested in production.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/copiousfreetime/kjess/issues/14#issuecomment-16358380
> .

## 

Rick Olson
http://github.com/technoweenie

**Comment by copiousfreetime** [comment]
I do believe I fixed something similar somewhere else. About to get on a plane. I'll have more details tonight.

**Comment by technoweenie** [comment]
Ah, it's [fixed in master](https://github.com/copiousfreetime/kjess/blob/master/lib/kjess/socket.rb#L226-L227).  If you could push an updated gem, I'd be most grateful.  Sorry for the noise!

**Comment by copiousfreetime** [comment]
I haven't pushed a new version yet? Damn, sorry. I'll do that tonight.

**Comment by eric** [comment]
I realized that I'm still running my fork.

I'll review what the differences are and see if there's still anything outstanding preventing me from using it.
