### ISSUE TITLE
Outstanding unmerged changes from my branch

### ISSUE THREAD

**Issue by eric** [copiousfreetime/kjess#15]
https://github.com/eric/kjess/compare/all-of-the-pull-requests

The biggest things look like:
1. fork protection to prevent accidental connection sharing
2. wrapping all exceptions in a KJess::Client::Error

**Comment by copiousfreetime** [comment]
Cool, I'll take a look, taxes today so probably tomorrow or wednesday

**Comment by copiousfreetime** [comment]
And with 96b01a607a099d765fa5d7d7128c39a19c6c3ed0 I think we are up to date.
