### ISSUE TITLE
Should KJess::Socket::Error be derived from KJess::Connection::Error?

### ISSUE THREAD

**Issue by eric** [copiousfreetime/kjess#19]
It seems like all exceptions coming from a `KJess::Connection` should be of the same type.

**Comment by copiousfreetime** [comment]
I don't think so. Not all Socket::Errors are Connection::Errors and vice versa. Also, isn't this now fixed with #17?

**Comment by eric** [comment]
It does not, because KJess::Errors are just re-raised without being wrapped. 
​
The reason why I would think it should be derived is all socket exceptions are related to the connection. 

​
I would expect to be able to catch a single class to capture all exceptions related to connection problems...

**Comment by copiousfreetime** [comment]
@eric can you see if kjess head works in the way you would expect now? You should be able to rescue KJess::NetworkError in your retry logic, and only have one rescue clause.
